spring:
  application:
    name: bank-card-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_cards_db
    username: postgres
    password: Aibek005
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public


server:
  port: 2005
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: MyJwtSecretKeyForBankCardApplication2024MustBeLongEnough
  expiration: 86400000

encryption:
  secret:
    key: MySecretKey12345

logging:
  level:
    root: INFO
    java16.bank: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
