spring:
  application:
    name: bank-card-service

#  web:
#    cors:
#      allowed-origins:
#        - http://localhost:3000
#        - http://localhost:8080
#        - http://localhost:5173
#      allowed-methods:
#        - GET
#        - POST
#        - PUT
#        - DELETE
#        - PATCH
#        - OPTIONS
#        - HEAD
#      allowed-headers:
#        - Authorization
#        - Content-Type
#        - Accept
#        - X-Requested-With
#        - Cache-Control
#      exposed-headers:
#        - Authorization
#        - Content-Disposition
#      allow-credentials: true
#      max-age: 3600


  datasource:
    url: jdbc:postgresql://localhost:5432/bank_cards_db
    username: postgres
    password: Aibek005
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: MyJwtSecretKeyForBankCardApplication2024MustBeLongEnough
  expiration: 86400000

encryption:
  secret:
    key: MySecretKey12345

logging:
  level:
    root: INFO
    java16.bank: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

